package com.erofeev.menu.menus;

public enum Menus {
	MAIN, VIEW, ACTION, CLONE, IMPORT, EXPORT, VIEWGUEST, VIEWROOM, VIEWSERVICE, ACTIONADD, ACTIONREMOVE, ACTIONCHANGE, CLONEROOM, EXPORTGUEST, EXPORTROOM, EXPORTSERVICE, FINISH, STOP
}
